### ISSUE TITLE
测试 梯度更新

### ISSUE THREAD

**Issue by Hurryliang** [xuecheng990531/EWSNet#2]
请问测试验证前为什么没加 with torch.no_grad()啊

**Comment by xuecheng990531** [comment]
如果不在意显存大小和计算时间的话，仅使用model.eval()已足够得到正确的validation的结果；而with torch.zero_grad()则是更进一步加速和节省gpu空间

**Comment by Hurryliang** [comment]
感谢您的回复。但是我注意到在执行代码时，如果不使用 with torch.no_grad():，在验证过程中梯度仍然会被更新，这意味着模型可还是会从验证集中学习信息。指标也会随着epoch增加而增加，f1甚至能到95以上。

**Comment by xuecheng990531** [comment]
按理说，虽然eval模式会进行梯度计算，但是他并不会进行反向传播，通常情况下不会对模型结果产生重大影响，因为梯度计算的结果不会被用于参数更新。如果觉得不可以的话，也可以改用`with torch.no_grad()`禁止梯度的计算再试试结果。谢谢您的问题！
